### ISSUE TITLE
d3.event.x and y are not the same as using regular D3

### ISSUE THREAD

**Issue by codydunne** [dsaffo/DESCVis#3]
When using `vc.drag()` instead of `d3.drag()`, the coordinates stored in `d3.event.x` and `y` are not the same as when using regular D3.

My particular code with the problem, for `.on('drag', ...)`
```js
d3.select(this)
    .attr('x', d.x = Math.min(width - hexWidth, Math.max(0, d3.event.x)))
    .attr('y', d.y = Math.min(height - hexHeight, Math.max(0, d3.event.y)));
```

You can see a full example in [the game I made with VC](https://codydunne.github.io/HeyThatsMyFish/). When the tiles or penguins are dragged, their top-left coordinate is moved under the cursor. Using plain D3, the elements kept their relative offset to the cursor.

**Comment by michaschwab** [comment]
Thanks Cody! This should be fixed now.
